languageCode = 'en-us'
title = "Simon's Website"
description = "My personal blog website"
source = "https://github.com/SimonWoodtli/simonwoodtli.com/"
baseURL = 'https://simonwoodtli.com/'
license = "Apache-2.0"
licenselink = "https://github.com/SimonWoodtli/simonwoodtli.com/blob/main/LICENSE"
copyright = "Simon D. Woodtli - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)"


## sets amount of entries shown in list pages per page
paginate = 30
# By default Hugo turns tags and categories on. This is to disable
# categories
[taxonomies]
  tag = 'tags'
# By default Hugo content folder and URL strucuture are the same.
# However I use /content/posts/timestamp/index.md, but still want the
# URL to inlcude the title instead of the timestamp.
[permalinks]
 [permalinks.page]
  posts = '/posts/:slug/'
  links = '/links/:slug/'

# Syntax higlighting from builtin chroma
[markup]
  [markup.highlight]
    noclasses = false
########################### RSS/Atom Settings ##########################
[params.author]
name = "Simon D. Woodtli"
uri = "https://www.simonwoodtli.com/"
email = "me@simonwoodtli.com"
twitter = "simonwoodtlidev"
image = "simonwoodtli.jpg"
[params.brand]
tagline = "Recent content on Simon's Blog"
icon = "img/favicon.ico"
logo = "img/logo.png"

# RSS limit, remove for unlimited posts
rssLimit = 100

[outputs]
# Output HTML, and ATOM on Home
home = ["html", "atom"]
# Output only HTML everywhere else
section = ["html"]
taxonomy = ["html"]
term = ["html"]

# Define a new ATOM output format
[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "atom"
mediaType = "application/atom+xml"

# Define a new ATOM media type
[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

